# Site settings
title: "Lorem Ipsum"
email: testing@email
description: "Hey look a description!"
baseurl: ""
url: "https://0x4a.github.io"
title_description: "A random collection of writeups, reviews, and rarambling about the secrets of the universe and whatnot.
testing linebreak
testing another linebreak"
title_image: "/J.jpg"
google_analytics: "UA-148080186-1"
disqus_account: 
github_repository: https://github.com/Dreamscent
addthis_id: wtfisthisfor
post_limit: 5

# Social usernames/URLs
twitter_username: 
github_username:  Dreamscent
instagram_username: 
reddit_username: 
linkedin_link: https://sg.linkedin.com/in/juliantanws
google_plus_link: 
stackoverflow_link: 
xing_link:
facebook_link:

# Footer
footer_left: "Made with <i class=\"fa fa-heart\"></i> by <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/jacobtomlinson/carte-noire\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
