# Site settings
title: "J's Corner"
email: testing@email
description: "J's stash"
baseurl: ""
url: "https://Dreamscent.github.io"
title_description: "Welcome to my Github Page! <br><br>
This is my random collection of writeups, reviews, and ramblings about the secrets of the universe and whatnot. Mainly security stuff.
<br><br>
"
title_image: "https://github.com/Dreamscent/Dreamscent.github.io/raw/master/images/J.jpg"
google_analytics: "UA-148080186-1"
disqus_account: 
github_repository: https://github.com/Dreamscent
addthis_id: 
post_limit: 5
future: false

# Social usernames/URLs
twitter_username: 
github_username:  Dreamscent
instagram_username: 
reddit_username: 
linkedin_link: https://sg.linkedin.com/in/juliantanws
google_plus_link: 
stackoverflow_link: 
xing_link:
facebook_link:

# Footer
footer_left: "Made with <i class=\"fa fa-heart\"></i> by <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/jacobtomlinson/carte-noire\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
