# Site settings
title: "Lorem Ipsum"
email: testing@email
description: "Hey look a description!"
baseurl: ""
url: "https://0x4a.github.io"
title_description: "A random collection of writeups, reviews, and ramblings about the secrets of the universe and whatnot. Don't take me too seriously :)
testing linebreak

testing another linebreak"
title_image: "https://lh3.googleusercontent.com/qTx5sApo3WNZR5e8lX-ROULQ3atkKWGX7W9qPs0ay-PPQzRo6B-feaGN-U_Ud8l6UhMErr3tTgbOj8sCCEYi2z-j5bPD6pb1oaS92FgPF4JgS-uu4r4PZH-1VtkoPWMqph3PjboYXgA51_xl5CL50VBGDzlOVbfLSDJcESZWcSYTqHjnsyY1j-yC2D8IGjny5MfMzbwEaOyeLXU9lhWbjmJMrVgJZtnmxGHPqZdLZj2pZscc67Te_zf_mFEeSRnaQLtit18j_c5Y8QUvYIBvpBt8Pn24M5UNQ33RI5M6BgmjE2-dCuWNZXetqLQvsSFiyBlOOUXpywlVSZteC-kbG4b49Nj6bRb1yumX11BxIqemI_w-_7y5etws3KeDgkN9TEc2TkVNBQIFWnzsKOV32iUDfD4d6gTD6Fcgt8RRDBpruW0jxXIMrP5dm6eAAdnpAOhPBK_I3cRWPvkmfcdBqlcb0kC4K9q58N2l7wBs8SyMuhjdAf1hK-wEktGGUtQ4TouUx2Nlq8W7n1108MaGlbYp6jw7o5W9uKeX9OhrXKJ43jBY-8NrJI03Gr_7Ns7BVt6GKHXWBlgB_qo-vvP1_QpL4Ec_OIjd27d2CEFygZ2ILpU0pv__40bTgz32nWUbWCnmPQ34z0gNDSJeFGNakHJybSX351Hq6a1v6pDhH8eiLrbMP_CF5cJ6oheM8ZA-KK5diaQIU3KMFk50SVqXmDu3udH6Dl91hcUIKJ-WNcYTsJt3=s100-no"
google_analytics: "UA-148080186-1"
disqus_account: 
github_repository: https://github.com/Dreamscent
addthis_id: wtfisthisfor
post_limit: 5
future: true

# Social usernames/URLs
twitter_username: 
github_username:  Dreamscent
instagram_username: 
reddit_username: 
linkedin_link: https://sg.linkedin.com/in/juliantanws
google_plus_link: 
stackoverflow_link: 
xing_link:
facebook_link:

# Footer
footer_left: "Made with <i class=\"fa fa-heart\"></i> by <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/jacobtomlinson/carte-noire\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
